var TECLAS = {
  UP: 38,
  DOWN: 40,
  LEFT: 37,
  RIGTH: 39
};

var TAMANIO_INICIAL_CULEBRITA = 3;
var CASILLAS_POR_NIVEL = 4;
var CASO_ESPECIAL_HABILITADO = true;
var NIVEL_MINIMO_CASO_ESPECIAL = 1;
var MENSAJE_CASO_ESPECIAL = "¿quieres casarte conmigo?";
var VELOCIDAD_INICIAL = 1000;
var VALIDAR_NIVEL_AL_AVANZAR = false;
